const languages=[
    {
        code:"en",
        name:"English",
        country_code:"gb"
    },
    {
        code:"es",
        name:"Spanish",
        country_code:"es"
    },
    {
        code:"fr",
        name:"Français",
        country_code:"gb"
    },
    {
        code:"it",
        name:"Italian",
        country_code:"it"
    },
    {
        code:"pt",
        name:"Portuguese",
        country_code:"pt"
    },
    {
        code:"ru",
        name:"Russian",
        country_code:"ru"
    },
    {
        code:"zh-CN",
        name:"Chinese (Simplified)",
        country_code:"zh-CN"
    },
    {
        code:"zh-TW",
        name:"Chinese (Traditional)",
        country_code:"zh-TW"
    },
    {
        code:"ja",
        name:"Japanese",
        country_code:"ja"
    },
    {
        code:"ko",
        name:"Korean",
        country_code:"ko"
    },
    {
        code:"ar",
        name:"Arabic",
        country_code:"ar"
    },
    {
        code:"hi",
        name:"Hindi",
        country_code:"in"
    },
    {
        code:"sv",
        name:"Swedish",
        country_code:"sv"
    },
    {
        code:"no",
        name:"Norwegian",
        country_code:"no"
    },
    {
        code:"da",
        name:"Danish",
        country_code:"da"
    },
    {
        code:"el",
        name:"Greek",
        country_code:"el"
    },
    {
        code:"tr",
        name:"Turkish",
        country_code:"tr"
    },
    {
        code:"af",
        name:"Afrikaans",
        country_code:"af"
    },
    {
        code:"sq",
        name:"Albanian",
        country_code:"sq"
    },
    {
        code:"rw",
        name:"Kinyarwanda",
        country_code:"rw"
    },
    {
        code:"ku",
        name:"Kurdish",
        country_code:"ku"
    },
    {
        code:"lo",
        name:"Lao",
        country_code:"lo"
    },
    {
        code:"ne",
        name:"Nepali",
        country_code:"ne"
    },
    {
        code:"sk",
        name:"Slovask",
        country_code:"sk"
    },
    {
        code:"sl",
        name:"Slovenian",
        country_code:"sl"
    },
    {
        code:"sw",
        name:"Swahili",
        country_code:"tz"
    },
    {
        code:"en",
        name:"English",
    country_code:"gb"
    },
    {
        code:"en",
        name:"English",
        country_code:"gb"
    },
    {
        code:"en",
        name:"English",
        country_code:"gb"
    },
    {
        code:"en",
        name:"English",
        country_code:"gb"
    },
    {
        code:"en",
        name:"English",
        country_code:"gb"
    },
    {
        code:"en",
        name:"English",
        country_code:"gb"
    },
    {
        code:"en",
        name:"English",
        country_code:"gb"
    },

]